eureka_hostname: service-registry
mongodb_hostname: customer-db

# Production environment
#mongodb_database_name: customerDB

# Development environment
mongodb_database_name: devCustomerDB

# Test environment
#mongodb_database_name: testCustomerDB

# Eureka properties
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka_hostname}:8761/eureka
  instance:
    hostname: localhost

# Server properties
server:
  port: 8091

# Application properties
spring:
  application:
    name: CUSTOMER-SERVICE
# MongoDB properties
  data:
    mongodb:
      database: ${mongodb_database_name}
      host: ${mongodb_hostname}
      port: 27017
  config:
    import: optional:settings.yml
