# Test environment
#mongodb_hostname: customer-db
#mongodb_database_name: testCustomerDB

# Server properties
server:
  port: 8091

# Application properties
spring:
  application:
    name: CUSTOMER-SERVICE
# MongoDB properties
  data:
    mongodb:
      database: ${mongodb_database_name}
      host: ${mongodb_hostname}
      port: 27017
  config:
    import: optional:settings.yml
  profiles:
    active: standalone
